apiVersion: v2
appVersion: 4.10.0
description: |
  Dependency-Track is an intelligent Software Supply Chain Component Analysis platform that allows organizations to identify and reduce risk from the use of third-party and open source components. Dependency-Track takes a unique and highly beneficial approach by leveraging the capabilities of Software Bill-of-Materials (SBOM). This approach provides capabilities that traditional Software Composition Analysis (SCA) solutions cannot achieve.
name: dependency-track
home: https://dependencytrack.org/
version: 1.6.0
icon: https://raw.githubusercontent.com/DependencyTrack/branding/master/dt-logo-black-text.svg
keywords:
 - security
 - dependency
 - dependency-track
 - OWASP
 - Supply Chain Component Analysis
maintainers:
- name: davidkarlsen
  email: david@davidkarlsen.com
- name: otterian
  email: eth0linak@gmail.com
sources:
 - https://docs.dependencytrack.org/
 - https://github.com/evryfs/helm-charts
dependencies:
# https://artifacthub.io/packages/helm/bitnami/postgresql/
- name: postgresql
  version: ~13.2.24
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
# https://artifacthub.io/packages/helm/bitnami/common
- name: common
  version: 2.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
